apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: travelers-cluster-issuer
    cert-manager.io/common-name: api.mulesoft-sb.ekslb.aws.travp.net
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"HTTPS","nginx.ingress.kubernetes.io/configuration-snippet":"rewrite ^/app-name(/|$)(.*) /$2 break;\n","nginx.ingress.kubernetes.io/rewrite-target":"/$2","nginx.ingress.kubernetes.io/ssl-redirect":"true"},"labels":{"business-group":"business-group-id","environment":"environment-id"},"name":"rtf-eks-ingress","namespace":"rtf"},"spec":{"ingressClassName":"rtf-nginx","rules":[{"host":"api.mulesoft-sb.ekslb.aws.travp.net","http":{"paths":[{"backend":{"service":{"name":"service","port":{"number":8081}}},"path":"/app-name","pathType":"Prefix"}]}}],"tls":[{"hosts":["api.mulesoft-sb.ekslb.aws.travp.net"],"secretName":"mulesoft-sb-eks-tls"}]}}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/app-name(/|$)(.*) /$2 break;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2022-05-26T13:29:44Z"
  generation: 9
  labels:
    business-group: business-group-id
    environment: environment-id
  name: rtf-eks-ingress
  namespace: rtf
  resourceVersion: "81864991"
  uid: ba41b135-fc55-4d87-b68b-8a117082483a
spec:
  defaultBackend:
    service:
      name: mule-clusterip-service
      port:
        number: 80
  ingressClassName: rtf-nginx
  rules:
  - host: api.mulesoft-sb.ekslb.aws.travp.net
    http:
      paths:
      - backend:
          service:
            name: mule-clusterip-service
            port:
              number: 80
        path: /app-name
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - api.mulesoft-sb.ekslb.aws.travp.net
    secretName: mulesoft-sb-eks-tls
status:
  loadBalancer:
    ingress:
    - hostname: acf3619f1a6cc42f086a9fabf7ca4c1a-a828acd015db45cb.elb.us-east-1.amazonaws.com
